resolver: lts-16.31
packages:
- .
extra-deps:
- gl3w-0.1.0
nix:
  packages:
    - alsaLib
    - pkgconfig
    - libGL
    - libGLU
    - glfw3
    - xorg.libX11
    - xorg.libXi
    - xorg.libXrandr
    - xorg.libXxf86vm
    - xorg.libXcursor
    - xorg.libXinerama
    - xorg.libXext
  pure: false
